apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: logger
spec:
  hosts:
  - "*"
  gateways:
  - my-gateway
  http:
  - match:
    - uri:
        exact: /colors
    route:
    - destination:
        host: colors
  - match:
    - uri:
        exact: /logger
    route:
      destination: logger-frontend
